### ISSUE TITLE
Positive IC50 value

### ISSUE THREAD

**Issue by XLuHouston** [paulgeeleher/pRRophetic#2]
Hi there,

Sorry, I have asked a lot of questions and I have to bother you again cuz I am performing some drug prediction analysis and I need to interpret the results.

I checked IC50 values in GDSC website and most of it are very small like 0.00035.
And the IC50 value I got from getGCPinfo() is really big (even some negative value) so this value should have been processed, but I think the transformation is not powertransformed in this part.

In the first time I thought it may be transformed by -ln (IC50), but in the Genome Research paper you mentioned that lower values of imputed response (estimated IC50) imply greater drug sensitivity, which means I am wrong. Because if the original IC50 = 0.0003, -ln(0.0003)=8 and -ln(0.0001)=9.
 
Sorry maybe you have explained it somewhere in your paper but I really miss it, so could you please tell me how to interpret the IC50 value in your data?

**Comment by paulgeeleher** [comment]
Hi, Can you post the code / results so I can reproduce what you are seeing?

**Comment by XLuHouston** [comment]
Sure.

```
Cisplatin.GCP <- getCGPinfo(drug = "Cisplatin", tissueType = "allSolidTumors", dataset = "cgp2014")
Cisplatin.GCP.ic50 <- Cisplatin.GCP[[1]]
Cisplatin.GCP.expr <- Cisplatin.GCP[[2]]; colnames(Cisplatin.GCP.expr) <- names(Cisplatin.GCP.ic50)
> Cisplatin.GCP.ic50
            5637           22RV1        23132-87           639-V           769-P           786-0           8505C 
        1.508200        3.230500        4.099700        1.773000        2.782200        1.496300        3.544400 
 ........   
    EFM-19          EFO-21          EFO-27           EGI-1       EPLC-272H             ES1             ES3 
        5.499900        3.516600        2.578700        2.407100        2.568100        0.023724       -0.146880 
 
 #prediction using my data as testmatrix
 predictedPtype <- pRRopheticPredict(testMatrix = as.matrix(log2(FPKM.HUGO[,rownames(annCol)] + 1)),drug = "Cisplatin",tissueType = "allSolidTumors",selection = 1)
```

Is there anything more you need?

**Comment by XLuHouston** [comment]
Sorry, I was wrong.
I have figured it out, the IC50 was Ln transformed.
Thank you.
